import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NotificationProvider } from "./components/shared/notify/notify-context";
import HeaderContainer from "./components/shared/header-components/headerContainer";
import { Suspense } from "react";
import LoadingApp from "./components/shared/loading/loading";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={<LoadingApp />}>
          <NotificationProvider>
            <HeaderContainer />
            {children}
          </NotificationProvider>
        </Suspense>
      </body>
    </html>
  );
}
